name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Use Yarn 1.17.2
      run: |
        npm install -g yarn@1.17.2    
    - name: yarn build
      run: |
        yarn install
        yarn build
